name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 3.0
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
      - name: Bundle install
        run: |
          gem install bundler:2.2.15
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Build with Jekyll
        run: |
          bundle exec jekyll build
